# Generated by Django 3.0.3 on 2020-02-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
